---
editor_options:
  markdown:
    wrap: 72
---

# Course Overview {.unnumbered}

This section is only relevant to students taking the MLDS course in the
academic year 2022-23.

## Welcome!

Data-driven decision making is now pervasive and impacts us all. Your
data is used by others to make decisions about who you are, how you will
behave, and what options should be made available to you. Predictive
models are used to decide anything from the promotion that is offered to
you by a retailer through to whether your loan application is granted by
a bank.

The ways in which these predictive models can fail mathematically form a
core part of the training for an aspiring statistician, data scientist
or machine learning practitioner. In contrast, the potential for ethical
failures in these same models is rarely covered in-depth during as part
of this initial training. As a result, these ethical modes of failure
are often not considered until those predictive models have been put
into production and are actively causing harm.

To prevent this harm, the ethical impacts of using data to make
decisions must be made core to the curriculum of both statistics and
data science. This course aims to address that gap.

The course takes a practical and technical approach to identifying these
ethical issues. It has a strong mathematical focus and will not not
require the authoring of extended essays or moral treaties. Throughout
the course, you will discover actionable ways in which these topics may
be integrated into a data science workflow at a range of levels.

## Module Description

This module will investigate the ethical implications of the new
capabilities offered by Data Science and Artificial Intelligence.

**Part 1** will begin by discussing the ethical use of data itself - the
raw materials of data science pipelines. It will then discuss sets of
principles that tech leaders and international bodies are adopting to
promote ethical use of data science and artificial intelligence
algorithms, including a discussion of real-world examples of failings
and adverse outcomes.

**Parts 2 and 3** will then revisit the issues explored in Part 1 in
greater technical detail. These parts will introduce data science
methodologies that provide novel solutions to ethical problems of old
such as explainability, prejudice and bias.

## Learning Objectives

1.  Recognise and accept responsibility for the societal impact of data
    science and machine learning technologies;

2.  Participate in the broader debate about the issues surrounding the
    use of data science and machine learning for prediction, decision
    making and knowledge generation tasks;

3.  Identify common ethical pitfalls of data science and ML algorithms
    via a mental "check-list" and evaluate the degree to which a given
    algorithm is likely to conform with ethical best practices.

4.  Formally test for common ethical pitfalls of data science and ML
    algorithms;

5.  Implement mitigation measures against the ethical risks posed by the
    use of data science and ML algorithms;

6.  Construct well-founded and evidence-based arguments with which to
    positively influence the actions of stakeholders and
    decision-makers;

7.  Take a systems perspective to holistically appraise data science
    projects on their ethical and societal impacts.

## Live Sessions and Office Hours

During the course we will have up to two hours of contact time per week:
a weekly office hour and a fortnightly live session. These sessions will
alternate between 9am and 4pm on Fridays each week.

**Live sessions** will mainly consist of guided group discussions to
further explore the topics covered each week. These sessions will be
recorded so that you may review them later in the course or if you
cannot attend due to time zone issues. Each live session will also have
some time allocated for questions on course material. These questions
can either be asked live or via the EdStem discussion forum.

**Office hours** are a more informal session dedicated entirely to
answering your questions and will not be recorded. These will by default
be a group session of up to 40 minutes. This allows you to benefit from
the questions asked by other students as well as your own. The final 20
minutes of each session will be reserved for 1-1 discussions. To arrange
such a meeting, please contact the course lecturer by email at least 1
hour before the office hour begins. If no 1-1 meetings are arranged then
this time may be used at the lecturer's discretion to extend the group
discussion.

## Assessment

Ethics Part 1 accounts for 20% of your overall grade for this module.
Ethics Part 2 and Ethics Part 3 each account for 40% of your overall
grade.

For Ethics Part 1, there will be two assessed elements: weekly
peer-reviewed written summaries of your assigned reading and one
summative assessment.\
You will have the opportunity to submit up to 6 reading summaries. These
will be peer-marked with these marks moderated by the course lecturer
and/or graduate teaching assistants. Your mark will be calculated as the
average of your 5 highest scoring submissions. In particular, this means
that you can miss one submission without any consequence.

**Note:** each reading summary requires you to write your own summary
and to provide feedback to other students.

The weekly deadline for your **written submission is Wednesday at 23:59
(UK)** and the weekly deadline for the peer-feedback is **Thursday at
23:59 (UK)**.

+------------+----------------+------------+------------+------------+
| Assessment | Description    | \% of      | Release    | Due Date   |
| type       |                | Ethics     | Date       |            |
|            |                | Module     |            |            |
+============+================+============+============+============+
| Reading    | Weekly         | 5          | **Weekly,  | **Following|
| Summaries  | summary of     |            | Friday     | Thursday   |
|            | one            |            | 09:00      | 23:59 (UK) |
|            | assigned       |            | (UK)**     | **         |
|            | reading        |            |            |            |
|            | and            |            |            |            |
|            | provision      |            |            |            |
|            | of             |            |            |            |
|            | peer-feedback  |            |            |            |
|            | for two        |            |            |            |
|            | other          |            |            |            |
|            | students.      |            |            |            |
+------------+----------------+------------+------------+------------+
| coursework | Individual     | 15         | **Friday   | **Monday   |
|            | short          |            | 25 Nov     | 05 Dec     |
|            | report.        |            | 2022,      | 2022,      |
|            | This will      |            | 09:00      | 23:59      |
|            | involve a      |            | (UK)**     | (UK)**     |
|            | mixture of     |            |            |            |
|            | worksheet      |            | [Week 8]   | [Week 11]  |
|            | style          |            |            |            |
|            | questions      |            |            |            |
|            | and a          |            |            |            |
|            | guided         |            |            |            |
|            | case-study     |            |            |            |
|            | to assess      |            |            |            |
|            | technical      |            |            |            |
|            | understanding  |            |            |            |
|            | of the         |            |            |            |
|            | course         |            |            |            |
|            | content        |            |            |            |
|            | alongside      |            |            |            |
|            | its            |            |            |            |
|            | implementation |          |            |            |
|            | and            |            |            |            |
|            | limitations    |            |            |            |
|            | when used in   |            |            |            |
|            | context.       |            |            |            |
+------------+----------------+------------+------------+------------+

: Ethics 1 Assessment Components
